### ISSUE TITLE
Problem with Ch_Hospitals scenery

### ISSUE THREAD

**Issue by DarkIgo** [d41k4n/hems_mission_generator#3]
X-plane is reporting a problem with loading CH_hospitals 
I double-checked I have all library listed but everything is okay and I also checked 
scenery pack config file and tried different order with no success.

Included log file
[Log_hems.txt](https://github.com/d41k4n/hems_mission_generator/files/7532814/Log_hems.txt)

**Comment by DarkIgo** [comment]
Installing HéliAlpes Swiss Pack and its required library fixed the issue now I only need to fix some helipads, because of default scenery mesh.

**Comment by d41k4n** [comment]
Thanks for reporting. This has now been fixed with commit [c41d86c3](https://github.com/d41k4n/hems_mission_generator/commit/41d86c30b755d10d01af51a535a8fd943fa94776) (re-download and re-install of the master branch is required, overwriting existing files).

The issue was due to accidental dependencies to the worldmodels lib. Neither the HeliAlpes scenery and/or worldmodels lib are strictly required.
